# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'dotenv'
Dotenv.load('.env')

default_platform(:android)

platform :android do
  desc "Build signed release APK"
  lane :signed_apk do
    gradle(
      task: "clean assemble",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file" => ENV["KEYSTORE_PATH"],
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASSWORD"],
        "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEY_PASSWORD"]
      }
    )
  end
  
  desc "Capture app screenshots"
  lane :screenshots do
  	gradle(task: "clean assembleDebug assembleAndroidTest")
  	screengrab
	end
	
	desc "Increment version code, set new version name and generate changelog"
	lane :release do
		changelog_from_git_commits(
  		merge_commit_filtering: "exclude_merges"
  	)
		versionName = prompt(text: "Version name: ")
		changelog = prompt(
    	text: "Changelog: ",
    	multi_line_end_keyword: "END"
  	)
		increment_version_code(
			gradle_file_path: "./app/build.gradle"
		)
		newVersionCode = android_get_version_code()
		changelog_file = File.join(__dir__, "./metadata/android/en-US/changelogs/#{newVersionCode}.txt")
		File.open(changelog_file, "w") do |file|
      file.puts(changelog)
    end
		android_set_version_name(
			version_name: versionName
		)
	end
end

